server:
  port: 8083

spring:
  application:
    name: qms-ticket
  datasource:
    url: jdbc:mariadb://localhost:3306/bank_qms_ticket?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: asahimaww1
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
